---
# handlers file for nginx_phpfpm
- name: restart nginx
  service:
    name: nginx
    state: restarted
  ignore_errors: yes

- name: restart php-fpm
  service:
    name: php8.1-fpm.service
    state: restarted
  ignore_errors: yes